import type { Lead, Doctor, Appointment, Condition, Specialty } from '@/types';

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1 (555) 123-4567',
    city: 'New York',
    symptoms: 'Severe headaches and nausea',
    preferredLanguage: 'English',
    source: 'Website',
    detectedConditions: ['migraine'],
    assignedAgent: 'agent1',
    stage: 'new',
    createdAt: new Date('2025-09-18'),
    updatedAt: new Date('2025-09-18'),
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+1 (555) 987-6543',
    city: 'Los Angeles',
    symptoms: 'Lower back pain after exercise',
    preferredLanguage: 'English',
    source: 'WhatsApp',
    detectedConditions: ['back-pain'],
    assignedAgent: 'agent1',
    assignedDoctor: 'doctor3',
    stage: 'contacted',
    createdAt: new Date('2025-09-17'),
    updatedAt: new Date('2025-09-18'),
  },
  {
    id: '3',
    name: 'Bob Johnson',
    email: 'bob@example.com',
    phone: '+1 (555) 456-7890',
    city: 'Chicago',
    symptoms: 'High blood sugar levels',
    preferredLanguage: 'English',
    source: 'Phone Call',
    detectedConditions: ['diabetes'],
    assignedAgent: 'agent2',
    assignedDoctor: 'doctor2',
    stage: 'qualified',
    createdAt: new Date('2025-09-16'),
    updatedAt: new Date('2025-09-17'),
  },
  {
    id: '4',
    name: 'Maria Garcia',
    email: 'maria@example.com',
    phone: '+1 (555) 321-9876',
    city: 'Miami',
    symptoms: 'Chest pain and shortness of breath',
    preferredLanguage: 'Spanish',
    source: 'Referral',
    detectedConditions: ['hypertension'],
    assignedAgent: 'agent1',
    assignedDoctor: 'doctor1',
    stage: 'booked',
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-16'),
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doctor1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@medcenter.com',
    phone: '+1 (555) 123-4567',
    specialties: ['cardiology', 'internal-medicine'],
    languages: ['English', 'Spanish'],
    insuranceAccepted: ['BlueCross', 'Aetna', 'Cigna'],
    location: 'New York, NY',
    isAvailableForTelehealth: true,
    availabilitySlots: [],
    rating: 4.8,
    experience: 15,
  },
  {
    id: 'doctor2',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@medcenter.com',
    phone: '+1 (555) 987-6543',
    specialties: ['neurology', 'pain-management'],
    languages: ['English', 'Mandarin'],
    insuranceAccepted: ['Kaiser', 'BlueCross', 'UnitedHealth'],
    location: 'Los Angeles, CA',
    isAvailableForTelehealth: false,
    availabilitySlots: [],
    rating: 4.9,
    experience: 12,
  },
  {
    id: 'doctor3',
    name: 'Dr. Emily Rodriguez',
    email: 'emily.rodriguez@medcenter.com',
    phone: '+1 (555) 456-7890',
    specialties: ['orthopedics', 'sports-medicine'],
    languages: ['English', 'Spanish', 'Portuguese'],
    insuranceAccepted: ['Humana', 'Aetna', 'BlueCross'],
    location: 'Miami, FL',
    isAvailableForTelehealth: true,
    availabilitySlots: [],
    rating: 4.7,
    experience: 10,
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'appt1',
    leadId: '4',
    doctorId: 'doctor1',
    slotId: 'slot1',
    date: new Date('2025-09-18T09:00:00'),
    status: 'scheduled',
    notes: 'Initial consultation for chest pain',
    followUpRequired: true,
    createdAt: new Date('2025-09-16'),
    updatedAt: new Date('2025-09-16'),
  },
  {
    id: 'appt2',
    leadId: '2',
    doctorId: 'doctor3',
    slotId: 'slot2',
    date: new Date('2025-09-18T10:30:00'),
    status: 'scheduled',
    notes: 'Back pain assessment',
    followUpRequired: false,
    createdAt: new Date('2025-09-17'),
    updatedAt: new Date('2025-09-17'),
  },
  {
    id: 'appt3',
    leadId: '3',
    doctorId: 'doctor2',
    slotId: 'slot3',
    date: new Date('2025-09-18T14:00:00'),
    status: 'completed',
    notes: 'Diabetes management consultation',
    treatmentPlan: 'Prescribed metformin, dietary changes',
    followUpRequired: true,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-18'),
  },
];

export const mockConditions: Condition[] = [
  {
    id: 'migraine',
    name: 'Migraine',
    description: 'Severe recurring headaches often accompanied by nausea and sensitivity to light',
    keywords: ['headache', 'migraine', 'nausea', 'light sensitivity', 'throbbing pain'],
    specialtyId: 'neurology',
  },
  {
    id: 'diabetes',
    name: 'Type 2 Diabetes',
    description: 'A chronic condition affecting blood sugar regulation',
    keywords: ['diabetes', 'blood sugar', 'insulin', 'glucose', 'thirst', 'fatigue'],
    specialtyId: 'endocrinology',
  },
  {
    id: 'back-pain',
    name: 'Lower Back Pain',
    description: 'Pain in the lumbar region of the spine',
    keywords: ['back pain', 'lumbar', 'spine', 'sciatica', 'muscle strain'],
    specialtyId: 'orthopedics',
  },
  {
    id: 'hypertension',
    name: 'Hypertension',
    description: 'High blood pressure condition',
    keywords: ['high blood pressure', 'hypertension', 'heart', 'chest pain'],
    specialtyId: 'cardiology',
  },
];

export const mockSpecialties: Specialty[] = [
  {
    id: 'cardiology',
    name: 'Cardiology',
    description: 'Heart and cardiovascular system',
    conditions: ['hypertension', 'heart-disease', 'arrhythmia'],
  },
  {
    id: 'neurology',
    name: 'Neurology',
    description: 'Brain and nervous system',
    conditions: ['migraine', 'seizures', 'stroke'],
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics',
    description: 'Bones, joints, and musculoskeletal system',
    conditions: ['back-pain', 'arthritis', 'fractures'],
  },
  {
    id: 'endocrinology',
    name: 'Endocrinology',
    description: 'Hormones and endocrine system',
    conditions: ['diabetes', 'thyroid', 'hormonal-disorders'],
  },
];